site_name: Sheriruth 官方Wiki
theme:
  name: 'material'
  extra_css:
    - assets/extra.css
markdown_extensions:
  - attr_list
nav:
  - 首页: index.md
  - 入门:
      - 世界观: 世界观.md
      - 属性:
          - 概述: 属性/概述.md
      - 等级: 等级.md